### ISSUE TITLE
Update version in sda-pipeline in BP SDA

### ISSUE THREAD

**Issue by pontus** [NBISweden/aida-data-hub#105]
It seems we sometimes get stalls while uploading, this was possibly fixed already in sda-pipeline. Check if we can/should update with GiantSloth and perform an upgrade if that's the case.

**Comment by pontus** [comment]
It seems an upgrade as done. I can also no longer trigger the issue trivially as I could before.

**Comment by shreyasshivakumara** [comment]
Great! I will close the issue then.
