### ISSUE TITLE
Get kubernetes training for AIDA Data Hub personnel

### ISSUE THREAD

**Issue by yohell** [NBISweden/aida-data-hub#109]
- [x] Get head count for [CKA](https://nbisweden.slack.com/archives/C032665J9QC/p1677510313916879) / [CKS](https://nbisweden.slack.com/archives/C032665J9QC/p1677510326788959)
- [x] ~Ask IT department to buy (T2303-01080)~ Response: They cannot.
- [ ] Check with home department if they can order directly.

**Comment by yohell** [comment]
IT department is currently investigating whether they can buy this for us through existing framework agreements. If not, then we can probably do a direct procurement ourselves.

**Comment by yohell** [comment]
Further delays at the university preferred provider. Hopefully we will get answers during next week.

**Comment by yohell** [comment]
No progress. IT department sent reminder to provider today.

**Comment by yohell** [comment]
IT department says they cannot order this for us. I've discussed with home department and asked administration to buy directly.

**Comment by ahembal** [comment]
another option may be this : https://www.manning.com/
