### ISSUE TITLE
Provide details to decide security model for providing Cytomine and other services

### ISSUE THREAD

**Issue by pontus** [NBISweden/aida-data-hub#117]
We should decide on the security abstraction layer we feel comfortable with for providing the Cytomine service.

We probably do not trust the cytomine service, assuming an attacker can get full access within such a container, can there be a breakout to the host?

There are a few common misconfigurations that could allow that:
* excessive `hostPath` access
* dangerous capabilities accessible (e.g. because of `privileged` container)
* excessive kubernetes privileges through a provided service account

assuming we are comfortable we can protect against such misconfigurations, do we believe the container environment is secure enough that it's difficult enough to break out of?

Not unimportant is that the resource consumption needed for using VM separation will likely be much higher. Using that approach will also lead to some new issues (e.g. network separation required, sharing GPU resources won't be possible, et.c).

This should produce the basis for a risk assessment enabling us to decide what is an appropriate separation mechanism from a security standpoint with the main options being VMs (likely with separate virtual networks for separate projects) or kubernetes namespaces (possible with some additional restrictions/security features).

**Comment by ahembal** [comment]
[This](https://resources.nvidia.com/en-us-accelerated-networking-resource-library/palo-alto-networks-intelligent?ncid=em-nurt-895830&mkt_tok=MTU2LU9GTi03NDIAAAGK12wMQZ-zcCrEe4M_SrmlDEWvkZKeJjIUFfzK87htmVaKwoF_m7okAnZU4eIOVxPACbEE8fPpSxYZUcX8fLqz7fUSCBx0zqLZdYOXFkve49GXRbjoEg&_pfses=c3VaUCNzzAN3StwKacRauTzh#cid=nbu02_em-nurt_en-us) quick video from nvidia is about network security, might not be directly related to this card, but i think it's good to know.
