### ISSUE TITLE
We should have an explicit discussion and risk considerations of the different security models for GPUs available

### ISSUE THREAD

**Issue by pontus** [NBISweden/aida-data-hub#131]
Most Nvidia GPUs offers virtualization through time slicing. 

Some specific product lines (e.g. A30, A100) also offers MIG (https://www.nvidia.com/en-us/technologies/multi-instance-gpu/) which offers compartmentalization with enforced resource usage restrictions for e.g. bandwidth.

A100/H100 also supports APM, which is used by e.g. [Azure for confidential computing](https://www.microsoft.com/en-us/research/blog/powering-the-next-generation-of-trustworthy-ai-in-a-confidential-cloud-using-nvidia-gpus/?ranMID=24542&ranEAID=TnL5HPStwNw&ranSiteID=TnL5HPStwNw-cR_1BUgo8P56zkdwyg95dA&epi=TnL5HPStwNw-cR_1BUgo8P56zkdwyg95dA&irgwc=1&OCID=AID2200057_aff_7593_1243925&tduid=%28ir__0wnlbzvzeckfbzd1eilkilu9qv2x63y2oef1fhq000%29%287593%29%281243925%29%28TnL5HPStwNw-cR_1BUgo8P56zkdwyg95dA%29%28%29&irclickid=_0wnlbzvzeckfbzd1eilkilu9qv2x63y2oef1fhq000) and protects the communication between the GPU compartment and the CPU (my interpretation).

We should produce the basis for a risk assessment.

I believe we can limit our supported use cases we need to address to SaaS services (although with user supplied AI models and software we do not trust).

**Comment by yohell** [comment]
Good idea! Who have the competence to discuss this in concrete technical terms? I can contribute a pretty good understanding of project desires and risk assessments, but I do not have sufficient tech insight for useful discussion. Should we try to engage NSC? SafeSpring?

**Comment by pontus** [comment]
Related reading https://www.cs.ucr.edu/~nael/pubs/ccs18.pdf.
