### ISSUE TITLE
Read and comment on AIDA Data Sharing Policy

### ISSUE THREAD

**Issue by yohell** [NBISweden/aida-data-hub#135]
Link: [AIDA Data Sharing Policy](https://datahub.aida.scilifelab.se/sharing/) [[gdocs format](https://docs.google.com/document/d/17MZJkNnopiRoEx4eYsi_rn-YPZH1AJbz0IxRRvcbWBk/edit#)]

It's been a while since anyone read this end-to-end, and thought about if the contents still make sense in light of any recent developments, or if things need to be updated, or even if the links still work, or if the outside world has changed so that the links now go to the wrong place.

Please read and reflect, and comment on anything weird.

You can use the comment function in the gdocs if you like!

**Comment by ahembal** [comment]
[This](https://data-guidelines.scilifelab.se/topics/gdpr-legal-reference/#legal-references-for-key-concepts) may be helpful as an extra reading material.
