### ISSUE TITLE
Extract dataset metadata as suggestion for landing page and mail as suggestions

### ISSUE THREAD

**Issue by pontus** [NBISweden/aida-data-hub#143]
To move along the dataset pages, it might be helpful if we mail suggestions that the contributors of three first dataset can then approve or comment on rather than waiting for them to provide them.

This would likely go somewhat like:

* Get dataset metadata files from archive
* Run the tooling developed by JP/EG to extract metadata
* Look for and do any obvious cleanup
* Mail as suggestions individually to the respective contributor
* PROFIT (hopefully) by getting okays

**Comment by shreyasshivakumara** [comment]
Get Varshi access to archive

**Comment by darthvader2** [comment]
Can we close this card? As we will be receiving the pilot datasets from 3 data nodes.
