### ISSUE TITLE
Keywords as bullet points

### ISSUE THREAD

**Issue by pontus** [NBISweden/aida-data-hub#144]
In the metadata TF meeting recently, there were some discussions about having keywords as a drop down menu which I thought meant people talked about how to enter the data, but maybe this was about having those as bullet points rather than on a single line (which would make sense to me visually).

**Comment by yohell** [comment]
"Drop down menus" seem to me to have to do with entering data, and not about displaying data, which "landing pages" is about. The present plan is to have the landing page information be generated automatically by data extraction/conversion tools produced by Sectra, and have the actual xml produced inspected / reviewed and possibly edited before submission by the contributor, like they would review everything before submission. Maybe this point about "drop down menus" can be forwarded to whomever is developing graphical front end interfaces for data entry (which I don't think anyone is, but if anyone would then that would be someone in wp3 or wp4, probably Cytomine). Maybe this should be the feedback to the reference group.

**Comment by darthvader2** [comment]
dataset page: - https://nbisweden.github.io/datasets.bp.nbis.se/mock_datasets/bp/B%20mock
