### ISSUE TITLE
More performance tests

### ISSUE THREAD

**Issue by pontus** [NBISweden/aida-data-hub#145]
Continue work in https://github.com/NBISweden/aida-data-hub/issues/71, at least https://github.com/NBISweden/aida-data-hub/issues/71#issuecomment-1467659411 but also get some values for latency, e.g. time required to fetch a 1 byte object.

So, at least:
* sustained read
* latency
* comparison between accessing a whole file and getting the last byte of a file needs to be done as well

It'd also be nice to check if byte-ranges are handled and how they affect latency (i.e. do we see the same time for getting data from the start of a a large files as the same amount of data from a small file - do we see different latencies for the same amount of data from the end of file)?

[Results from performance test](https://docs.google.com/document/d/1D00li27LCpO_jTgXway2UVr37akHFdCtqGDh8FlkuYA/edit#heading=h.srjs69o3n72n) - WIP

**Comment by shreyasshivakumara** [comment]
My plan to is to do the following test performances multiple times:
1. Large Object performance 
2. Small object performance

**Comment by ahembal** [comment]
[Here](https://drive.google.com/drive/folders/19MEooa_2q5iHsR1BSio7HU4s4k2cRk-x?usp=drive_link) are some documentation about the work that has been done

**Comment by pontus** [comment]
Can we please report the results (i.e. estimated sustained bandwidth and how byte-range requests work) in the issue?

**Comment by ahembal** [comment]
Summary:
The performance testing of the server using async testing with byte-range requests yielded consistent results. The average timing per kilobyte ranged from approximately 0.344995 milliseconds to 4.557529 milliseconds.

Estimated Sustained Bandwidth:
Based on the average timing per kilobyte, we can estimate the sustained bandwidth of the server. By converting the average timings to seconds per megabyte (ms/MB), we can approximate the sustained bandwidth:

Minimum average timing: 0.344995 milliseconds/kilobyte
Sustained bandwidth: 2.91 GB/s

Maximum average timing: 4.557529 milliseconds/kilobyte
Sustained bandwidth: 0.22 GB/s

These estimated sustained bandwidth values indicate the server's ability to consistently deliver data at different rates, depending on the average timing per kilobyte.

It's important to note that the effect of caching on the server's performance cannot be precisely determined without access to the server or CDN configuration. However, the consistent performance across the tested links suggests that the server is responding reliably to byte-range requests.

Further work can involve disabling caching and performing additional performance testing to evaluate the impact of caching on the server's response time. Additionally, ongoing performance testing within the applications deployed on the platform can provide insights into the server's performance in real-world scenarios.

**Comment by pontus** [comment]
A factor 10 is much higher than expected difference for sustained measurement, what's the size of data used?

(Looking at speed for units such as a kilobyte and extrapolating from there doesn't make sense in most cases, instead the calculation is the entire amount of data transferred divided by the entire time the transfer took.)

**Comment by ahembal** [comment]
:) Thank you for pointing out the correct approach for calculating sustained bandwidth. However, [Shreyas has done some work](https://docs.google.com/document/d/1D00li27LCpO_jTgXway2UVr37akHFdCtqGDh8FlkuYA/edit#heading=h.srjs69o3n72n) on sustained reading with big files before me, so I preferred to focus on byte-ranges performance, this is why the data size looks relatively small. Another limitation of this test was the publicly available data in the archive is not sufficient. The size of the biggest file in the available files to download is 17MB.

**Comment by ahembal** [comment]
In the performance test for fetching **18294748 bytes** of data (**approximately 17MB**) from an object storage system, the average time taken was **0.241 seconds**. This indicates the time required to retrieve the entire object.

For fetching only the last 10 bytes of the object, the average time was **0.040 seconds**. This measures the time taken to retrieve a small portion of the data.

**The standard deviation** (STDEV) for the full object was **0.213 seconds**, indicating the variation or spread of the individual latency measurements around the average.

For the last 10 bytes, **the standard deviation** was **0.013 seconds**, suggesting a relatively lower variability in the latency measurements for this smaller data subset.

These measurements provide insights into the performance of the object storage system in terms of data retrieval. The average time and standard deviation values allow for assessing the system's consistency and responsiveness in handling different data sizes.

It's important to note that these results are specific to the tested scenario and may vary depending on the specific setup, network conditions, and configuration of the object storage system. Further testing and analysis can help in evaluating and optimizing the system's performance for specific use cases, such as medical image storage and retrieval.

**Comment by ahembal** [comment]
The other part of the testing was sustained reading from the backend. s3cmd is used to measure the data transfer rates for two different datasets sizes (10GB and 30GB) (one big file). The tests were performed on two different networks, Safespring and Eduroam.

Results for the 10GB Dataset:

Safespring:
Test 1: Transfer rate of 209 MB/sec
Test 2: Transfer rate of 199 MB/sec

Eduroam:
Test 1: Transfer rate of 150 MB/sec
Test 2: Transfer rate of 151 MB/sec

Results for the 30GB Dataset:

Safespring:
Test 1: Transfer rate of 198 MB/sec
Test 2: Transfer rate of 189 MB/sec

Eduroam:
Test 1: Transfer rate of 142 MB/sec
Test 2: Transfer rate of 156 MB/sec
