### ISSUE TITLE
Reach out to DGX-2 users to see what they would like to get out of the next system

### ISSUE THREAD

**Issue by pontus** [NBISweden/aida-data-hub#148]
To be able to come up with a fit-for-purpose design of the next generation secure data processing service, we should learn what the purpose is, or will be. 

To this end, we should seek input from current and past users of the DGX-2 service, who have appreciated using the service. Maybe we should prepare a meeting? Maybe we should put together a survey as prep?

We want the best possible user experience, given the user needs, so we need to understand the user needs. For example, what services / modes of access would be most suitable? 

Some items to raise; do they want for example:

* Remote desktop? With preinstalled software? (Which?)
* Connection to private Sectra PACS in the cloud?
* SSH to bash shell?
* Root privileges?
* Jupyter notebooks?
* Orthanc? For example as DICOM endpoint for data ingress?
* Data download without DPA (for example through sda-cli)? (Requested by at least 1 researcher, who has their own secure servers, so wanted data, and did not need to otherwise use our actual service beyond the initial download of data, in which case signing a DPA to get access to a service you are not going to use seems like nonzero effort for something you don't actually want.)

It would be very good to know what the feature wish list would look like if prioritized based on user needs. Since we do not have unlimited resources, the actual feature set will be strongly influenced by what's easy to do as well as what would be most useful, but we do want to make sure we don't mistakenly drop any major usability items.

**Comment by pontus** [comment]
Batch?

**Comment by ahembal** [comment]
[Slurm](https://slurm.schedmd.com/overview.html)

**Comment by pontus** [comment]
I've started a document that could be used for this (through allowing users to comment as discussed?).

https://docs.google.com/document/d/1G4IT8CLNtv5XmXoNUVMMCt_6WMdeSpgXfkiLi5OaMng/edit?usp=sharing

**Comment by pontus** [comment]
Check with Caroline about newsletter.
