### ISSUE TITLE
Clean up old DGX-2 projects

### ISSUE THREAD

**Issue by shreyasshivakumara** [NBISweden/aida-data-hub#151]
This card was "Clean up in CMIV Firewall", but I'll reopen and rework this card a bit.

Prep work was is documented in this sheet: [CMIV firewall cleaning](https://docs.google.com/spreadsheets/d/19Ugkj6LNiiFDpOgLv8zzKpWB0mP7w9GYWTNL3EoNQug/edit#gid=0)

Consider each project and whether it should be deleted outright, and if so follow all the steps in [Remove project](http://130.236.251.132/#remove-project) in the DGX-2 admin docs.

If only some IP addresses should be deleted, review the steps in Admin docs [Remove project](http://130.236.251.132/#remove-project) that pertain to IP and mac addresses, including IP address assignment, policy & objects, and projects.yaml.

Consider whether the instructions for IP allocation removal are easily understood from the Remove project docs. If they are not, try to condense some instructions for a separate "Remove IP allocation" section in the DGX-2 admin docs. Do not hesitate to get feedback immediately (or at the latest before proceeding with deleting stuff).

Old card text here:
> There are IPs in the firewall that are being used by old DGX-2 projects. Unassign the IPs from the projects in the firewall. > Cross-check the projects that are currently not in use with the [google sheet](https://docs.google.com/spreadsheets/d/1wA7H3Uh53ADVYptiQWXROnMD67HvPOAwSvW20EnzlFM/edit#gid=2026064636).
>
> - [x] Remove old/unnecessary IPs from the CMIV firewall

**Comment by ahembal** [comment]
last check before cleaning: https://docs.google.com/spreadsheets/d/19Ugkj6LNiiFDpOgLv8zzKpWB0mP7w9GYWTNL3EoNQug/edit?usp=sharing

**Comment by yohell** [comment]
IP reservations are still in firewall config, and mac-to-ip mappings still in projects.yaml.
