### ISSUE TITLE
Onboard Erik

### ISSUE THREAD

**Issue by yohell** [NBISweden/aida-data-hub#158]
- [ ] Ensure [onboarding doc](https://docs.google.com/document/d/19mAGWpJnjpQMxJ7ROFWofz86ScvEaokpWkl7JorHxmY/edit#heading=h.r205qzg1p6mu) is up to date

**Comment by pontus** [comment]
Library/skillport reference?

**Comment by pontus** [comment]
Summer activity to be scheduled.
