### ISSUE TITLE
Support system

### ISSUE THREAD

**Issue by pontus** [NBISweden/aida-data-hub#161]
We should look into having a ticketing system to avoid issue communications in personal e-mails (which can get lost/not followed up on or not handled during vacation/sick leave).

**Comment by yohell** [comment]
We could consider using Github issues, since we're already using GitHub, and getting better at GitHub is probably a useful skill for AIDA Data Hub staff and and users. We could consider using what NBIS uses (redmine, I think?) if we need to be able to handle tickets with confidential information in them. Otoh, "handling tickets with confidential information in them" may not be a wise course of action, as we should do proper security, not security theater.

**Comment by ahembal** [comment]
Github issues?

**Comment by yohell** [comment]
I updated my comment above, but in case there's any doubt, GitHub Issues are for example this: https://github.com/aidadatahub/aidadatahub.github.io/issues

**Comment by ahembal** [comment]
how about if we use one of Open-source Self-Hosted Ticketing Systems?

**Comment by yohell** [comment]
Currently the aida-data@nbis.se is cc to sharing requests, and we have an aida-compute@nbis.se email list with sysadmins on it (not used, because we prefer to direct people to the all-to-all #aida-dgx2 channel.

We also have the MS Teams team CMIV IT, for CMIV IT issues.

**Comment by ahembal** [comment]
I can try to demo [this one](https://pypi.org/project/django-helpdesk/) if you would like to see

**Comment by ahembal** [comment]
[SciLifeLab OrderPortal](https://orderportal.scilifelab.se/) 


Features

- Allow a user (researcher) to register an account, which is enabled by the facility staff.
- Allows system administrators to create predefined forms with a specific set of input fields.
- Allow the user to specify an order according to one of the predefined forms.
- Allow input from the user of required project data, such as sample sheets.
- Allow the user to submit the order to the facility.
- The facility staff can review, accept or decline an order, depending on the configuration set up by system administrators.
- Let the facility staff keep track of review and agreements.
- Allow attaching files to an order.
- Display project status reports.
- Allow keeping track of Key Performance Indicators (KPIs), facilitating resource usage reports for the facility.

**Comment by pontus** [comment]
@eryl and @yohell  has had discussions with other support functions and it seems like we'll align with the rest of NBIS on Redmine.
