### ISSUE TITLE
Long term system documentation strategy

### ISSUE THREAD

**Issue by pontus** [NBISweden/aida-data-hub#166]
How do we want to work with administrative documentation long term?

**Comment by pontus** [comment]
If we need to have many places for documentation going forward, can we make a single entrypoint?

**Comment by pontus** [comment]
AIDA Data hub uses confluence for user documentation, going forward?

**Comment by pontus** [comment]
Epic?

**Comment by yohell** [comment]
Depending on the audience (public? users? members? admins?) and purpose (admin? usage?) we could consider using the overhauled website (make separate pages with info and docs for each service for example here: [data-science-platfor](https://datahub.aida.scilifelab.se/preview/data-science-platform/#add-on-services) or similar) or under [docs](https://datahub.aida.scilifelab.se/preview/docs/)?

**Comment by eryl** [comment]
Create github repo for this under the NBIS organization. No actual secrets.

**Comment by pontus** [comment]
Done by #702.
