### ISSUE TITLE
Deploy substra on a local setup

### ISSUE THREAD

**Issue by pontus** [NBISweden/aida-data-hub#175]
Do a deploy of Substra (https://docs.substra.org/en/stable/operations/overview.html) in a local environment to get an overall feel of the product.

**Comment by shreyasshivakumara** [comment]
https://bigpictureeu.sharepoint.com/Meetings%20%20Webinars/20221125%20Federated%20Learning/Federated%20Learning%20for%20digital%20histopathology_%20challenges%20and%20opportunities.pdf
