### ISSUE TITLE
Integrate OIDC authentication for harbor 

### ISSUE THREAD

**Issue by darthvader2** [NBISweden/aida-data-hub#202]
How to connect a service to the LifeScience AAI - https://docs.google.com/document/d/17pNXM_psYOP5rWF302ObAJACsfYnEWhjvxAHzcjvfIE/edit

**Comment by shreyasshivakumara** [comment]
https://docs.google.com/document/d/17pNXM_psYOP5rWF302ObAJACsfYnEWhjvxAHzcjvfIE/edit
