### ISSUE TITLE
Explore solutions for offering Jupyter in Kubernetes

### ISSUE THREAD

**Issue by pontus** [NBISweden/aida-data-hub#223]
Assuming we do run a kubernetes cluster internally for other services we offer on CMIVDB, develop a solution for that (either test running so completely by ourselves or adapt a ready-made solution) that offers Jupyter (preferably with object backend for persistence although that isn't a strict requirement).

**Comment by darthvader2** [comment]
https://z2jh.jupyter.org/en/stable/

Jupyter hub for kubernetes seem to offer more flexible solution and can be deployed using helm.

**Comment by ahembal** [comment]
So it seems kubeflow is too heavy for our needs now, it requires too much computing pwr and storage, so our thought is continuing with jupyterhub. https://jupyter.org/hub
