### ISSUE TITLE
Improve DGX-2 user documentation to use venv for persistence

### ISSUE THREAD

**Issue by pontus** [NBISweden/aida-data-hub#233]
Current documentation could probably be improved to help installing things where they will persist between machine recreations (e.g. venvs).

**Comment by ahembal** [comment]
https://scilifelab.atlassian.net/wiki/spaces/aida/pages/1235189793/AIDA+DGX-2+Service#What-about-Anaconda
https://scilifelab.atlassian.net/wiki/spaces/aida/pages/1235189793/AIDA+DGX-2+Service#Managing-your-session

Are these relevant?

**Comment by pontus** [comment]
Reread and now consider good enough.
