### ISSUE TITLE
Create new projects for Claes

### ISSUE THREAD

**Issue by shreyasshivakumara** [NBISweden/aida-data-hub#237]
Create new projects
- [ ]   IDxPLiver1 project
- [x]   GenomicsVis project

**Comment by shreyasshivakumara** [comment]
I am still working on it. I will help Claes and others upload data to idxpliver project and then, we can close this card.

**Comment by pontus** [comment]
Status unknown? Asked Claes if he knew now.

**Comment by shreyasshivakumara** [comment]
Hi Pontus! This card is still my responsibility, I have told them I will help them upload data and create credentials for Claes and Thomas for the IdxPLiver project. Can I still be assigned to it?

**Comment by pontus** [comment]
Is this still a thing or can it be closed?

**Comment by betuleren** [comment]
It was completed yesterday; so, it can be closed now.
