### ISSUE TITLE
Test deployment of GDI starter kit

### ISSUE THREAD

**Issue by yohell** [NBISweden/aida-data-hub#245]
All in Cortex should do this, to get familiarity with the software stack we will use for next gen AIDA Data Hub platform.

We did this at the [AIDA Data Hub Tech seminar on Sep 1](https://docs.google.com/document/d/1ig3fYTya8jf-RFDwGdk2IvQjQn_K7mzzwOoWv1frPBU/edit#heading=h.ucsrnvbsbdxm). Will revisit on Sep 15. 

GDI GitHub org: https://github.com/GenomicDataInfrastructure
Starter kit main repo: https://github.com/GenomicDataInfrastructure/starter-kit
Deployment notes: https://github.com/GenomicDataInfrastructure/starter-kit-se-deployment-notes

- [x] Deploy GDI starter kit
- [ ] Make it work, understand what parts do what, if you do not understand: ask a friend. 
- [ ] Make it break, do weird stuff to it and see in what manner it explodes. Then redeploy.
- [x] Deploy on your own laptop, deploy in a cloud.
- [ ] Find a friend to test your deployment
- [ ] Find a friend and test their deployment
- [x] Report any bugs or inconveniences to giant sloth. 
- If you lack examples, ask giant sloth.
- 

Some actions you can try:

- Try triggering ingesting for files that don't exist, then after a while upload the file and ingest it
- [ ] Find documentation that explains how to ingest files.
- Shut down rabbit mq, try ingesting files
- Try downloading with rabbitmq shut down
- [ ] Find documantation about how to download the data from storage
- Bring up rabbitmq, shut down database
- Try ingesting files
- Try downloading files
- Bring up database 
- Try renaming (moving out of the way) files from backend storage and see what happens when downloading
- [ ] Find documantation (or create) that shows where the backend is and explains how to access it.
- Restore file and see what happens when downloading

A bit harder; pick one of the files from the archive, do the work needed to get its clear text contents.

**Comment by pontus** [comment]
https://github.com/GenomicDataInfrastructure/starter-kit-se-deployment-notes
