### ISSUE TITLE
News item on new Support function and workshops for the CMIV linkedin page

### ISSUE THREAD

**Issue by yohell** [NBISweden/aida-data-hub#266]
Something like:

* AIDA Data Hub now has a support function, 
* where researchers in Swedish medical imaging diagnostics can get help with AI research; 
* Just held its first training event for an audience of ~45 AI researchers in AIDA on the topics of X and Y, 
* more events like this are being planned, 
* please visit website or contact us at email@xxx to get in touch
* Maybe include an image?

As short as possible is probably good

The sender should be CMIV and the audience should probably be CMIV and the world.

Maria might be able to comment on targeting/phrasing etc to make it impactful

**Comment by eryl** [comment]
Text draft can be found here
https://docs.google.com/document/d/1m_WuXxFjwJp5gpoUnBHesuDCarBt_MODCzYz4226oHI/edit?usp=sharing

images here:
https://drive.google.com/drive/folders/1W9pna-3NgiHUToLs48pmgHCYpWaEA_f4?usp=sharing
