### ISSUE TITLE
Check if we can deploy SlideTap on-platform

### ISSUE THREAD

**Issue by yohell** [NBISweden/aida-data-hub#283]
Investigate if it would be possible for us to deploy this in the infrastructure.

Erik and JoelP may be willing to assist.

**Comment by ahembal** [comment]
I sent a message to Erik to arrange a meeting. @yohell or @pontus, could you put some text here about what we want to get out of this app? So that I can use the text as a context when I meet them. 

I also see the Bigpicture label on this card, does that mean we want to use it for BP as well, even though Joel P. mentioned before that this app needs to be used within the hospital network?

**Comment by yohell** [comment]
I figured general context belongs in the Epic, so I put it there, so we wouldn't have to repeat context on all the cards in it. Was that the right idea? Do you have questions beyond what's there?

**Comment by ahembal** [comment]
Great! I actually forgot to check the Epic, now it's more clear to me. 
With this, I just learned from Daniel (CMIV-IT) that we have a research PACS at CMIV for researchers. Shall I initiate an access request to use for this purpose, so we can try to run SlideTap on that and somehow submit test dataset to the BP deployment? How does this sound?

**Comment by yohell** [comment]
Nope, sounds bad! :) LiU will not submit datasets to Bigpicture (at least until data sharing agreement processes are done, and GDPR roles have been agreed).

**Comment by ahembal** [comment]
Some comments are copied here:
"
You can likely run SlideTap from anywhere, but I guess what you want to do with it might be limiting. I.e. there are questions regarding:

- Do users want to have non-anonymized data outside their control?
- Converting files can be computationally expensive. Who pays?
- What about storage?

I have noticed two use cases being proposed for running SlideTap on platform:

- Use to view and further curate existing datasets. This should not require so much compute and maybe not so much storage, and the data should already be anonymized.
- For submitters that dont have the infrastructure to run it on site. Here the above questions are relevant
"
