### ISSUE TITLE
harbor helm repository considerations

### ISSUE THREAD

**Issue by pontus** [NBISweden/aida-data-hub#288]
As the  harbor helm repository wasn't flexible enough to support installations that run in the security configured cluster currently used for bigpicture, we had to roll our own.

That allowed us to progress, but now we need to decide about how to handle that.

* We can make a PR to the original [harbor chart](https://github.com/goharbor/harbor-helm), but it seems it's not very actively maintained regarding contributions, so it might not be evaluated for some time.
* We can stay leave it be until we have to do something
* We can follow along, rebasing upon the latest release every now and then.

Think of what we should do.

(Regardless of this, we'll need to have monitoring of advisories of harbor and react appropriately if anything happens).

**Comment by darthvader2** [comment]
Rebase to default directory structure and package releases as ZIP file, similar to SDA helm repositories.  Don't want to proceed with it until S3 backend is integrated.
