### ISSUE TITLE
Deploy Cytomine in AIDA Data Hub safespring environment

### ISSUE THREAD

**Issue by shreyasshivakumara** [NBISweden/aida-data-hub#29]
Checklist for this issue:
- [ ] Ensure Betul and Emre have access to AIDA Datahub safespring environment
- [ ] Deploy Federated Node HA-proxy - [repo link](https://github.com/NBISweden/Zombie-playground/tree/federated_node_safespring)
- [ ]  Deploy Federated Node Main Cluster - [repo link](https://github.com/NBISweden/Zombie-playground/tree/federated_node_main_cluster) 
- [ ] Deploy Cytomine in AIDA Data Hub Safespring environment

**Comment by ahembal** [comment]
@betuleren maybe you also want to assign yourself to here
