### ISSUE TITLE
Develop scheduling modes for SDS NG

### ISSUE THREAD

**Issue by pontus** [NBISweden/aida-data-hub#311]
The next system will offer different services, released in waves, some might make sense to have always available (jupyter?) whereas some needs to be turned on and off (project VMs?).

It's probably good to map out and get a common understanding of what makes sense.

Similarly, it might make sense to start deciding how these things should work for the users (like a calendar schedule for VMs compared to a token/quota model where you are not guaranteed to be able to start machines at any specific time).

**Comment by yohell** [comment]
When should this be done? When a use case has need of it? I suppose we know of a few must-haves where the choice is clear (?) like project VMs, which we can/must address first before investing effort into this? When do we have enough information to be able to reason about this?

**Comment by eryl** [comment]
We'll mainly use a cloud like model for now. A question is if we can handle reservations (e.g. for workshops or time crititical work).
