### ISSUE TITLE
Contact Nanjiang and Johan to follow up on ideas from Dev days Linköping for ways to improve collaboration

### ISSUE THREAD

**Issue by yohell** [NBISweden/aida-data-hub#353]
Link for [the document.](https://docs.google.com/document/d/1D6avIfKxgrCZFBUt5VbkTrY-iBXdpbh5L4EPOmv3wWA/edit#heading=h.wpci4cmubnls)

**Comment by pontus** [comment]
Try to talk through the list of ideas and see what we think are important now.

**Comment by ahembal** [comment]
Here are the point to take action:

- Identify goals and outcomes from collaboration  

> 

- Knowing other’s interests, experiences and expertise  
- Keeping people updated about our work, for example using demos at joint sprint review, status updates.
- Defining the problem in general terms  

> 

- Knowledge sharing? Are there places where workflows can be more efficient?
- Knowledge or interest “tribes” 
-- Like Frontend-tribe with monthly knowledge sharing meetup 
-- Hackathon?

> 

- General onboarding (all new hires arriving same day) where we explain them about the organization in the first months (solving root issue of explaining every year what everyone does).
