### ISSUE TITLE
Offboarding of Shreyas

### ISSUE THREAD

**Issue by pontus** [NBISweden/aida-data-hub#356]
Hand off things, add things we think of here while he's available.

https://docs.google.com/document/d/14G7JmrP6GLrCS5DhifhbjOqv6D2qjEPvH60NRUQbZwA/edit#heading=h.29duxmfom4jp

**Comment by shreyasshivakumara** [comment]
LINK WITH PERMISSIONS: https://docs.google.com/document/d/14G7JmrP6GLrCS5DhifhbjOqv6D2qjEPvH60NRUQbZwA/edit?usp=sharing

I couldn't edit the card hence I commented
