### ISSUE TITLE
Add data type to the data acquisition priorities, to enable collection of MRI-histology data.

### ISSUE THREAD

**Issue by yohell** [NBISweden/aida-data-hub#37]
Exact wording is: "MRI and histology of excised meningioma tumor samples", to be appended to the prio list

- [x] Work with contributor and clinical council to get exact wording
- [x] Append data type to prio list.

**Comment by pontus** [comment]
Fixed by https://github.com/aidadatahub/aidadatahub.github.io/pull/57.

**Comment by pontus** [comment]
Or maybe we leave these open until review?

**Comment by ahembal** [comment]
can we close this now :)
