### ISSUE TITLE
Refresh Cytomine to the latest community edition

### ISSUE THREAD

**Issue by pontus** [NBISweden/aida-data-hub#384]
Cytomine regularly release updates of their community edition. We should update to the latest release.

Specifically, we want to do this to have an easier upgrade later on if Cytomine release a version they would like to showcase on the annual meeting (which they have hinted about).

**Comment by ahembal** [comment]
[PR](https://github.com/NBISweden/cytomine-bp-helm/pull/29) was closed. Pontus is reformatting the scripts, it's coming with quite a lot of changes.
