### ISSUE TITLE
Create dataset for Berggreen project

### ISSUE THREAD

**Issue by betuleren** [NBISweden/aida-data-hub#39]
[AIDA Data in routine](https://docs.google.com/document/d/1FOb9YD_w_8SabCAbfWXHuKwAwhPyFBPKlVWuOTTwBF0/edit#heading=h.r3xqw63duao8)
- [x] Contact the project lead
- [ ] Check if the dataset is appropriately anonymized and is legal for sharing.
- [ ] Prepare the legal agreements if needed
- [x] Get approval from the Clinical council for prioritizing this data type
  - [x] Contact project lead for suitable data type description.
- [ ] Upload the data
- [ ] Create a public dataset register page

**Comment by pontus** [comment]
Can we do this, @yohell?

**Comment by pontus** [comment]
Can we do this, @yohell?

**Comment by shreyasshivakumara** [comment]
Last reminder will be sent today by Betul
