### ISSUE TITLE
Investigate IAM solutions 

### ISSUE THREAD

**Issue by pontus** [NBISweden/aida-data-hub#415]
For Cytomine were we intend to let people launch instances for specific datasets, we probably will not be directly using an SP configured in LS Login, but rather offer internal OpenID Connect endpoint(s) that relay to LS Login.

We also probably can't expect to use Perun facility management for access control for these instances, but will rather have to offer a way to manage that through the instance spawner, pushing identities of users that should have access into this solution

Keycloak should probably be an alternative, are there others?

Requirements:

* Act as "relay" (IdP for OIDC/OAuth2, SP towards OIDC or SAML)
* Support multiple "client SPs", configured "dynamically"
* Support access control/authorization for "client SPs", refusing authentication for users not in some predefined set.

Desirable:
* Pre-built images
* Kubernetes support, e.g. operator

**Comment by ahembal** [comment]
I'll [prepare](https://docs.google.com/document/d/1bnRDka5-513GQymOmQlEh21-k2w4dJ1d_uhWkVrSL5I/edit) a presentation to discuss this at Tech seminar.
