### ISSUE TITLE
Investigate delivery options for SDS system

### ISSUE THREAD

**Issue by pontus** [NBISweden/aida-data-hub#416]
We are writing procurement open-ended such that the vendor can offer installation services or not. For the case where it's not included, we need to figure out how we want to handle it/what our options are.

* Can we get delivery to Norrköping (RÖ) and have the contents stored securely until we can start installation
* Delivery to Linköping, stored securely at CMIV and then we rent a small truck for delivery to Norrköping?
* Other options?

(We probably should not be able to expect a delivery date, and it may be that there are multiple deliveries where only one is announced.)

**Comment by yohell** [comment]
RÖ says they can receive and securely store the equipment in Norrköping until we can rack it.
