### ISSUE TITLE
Set up a private Cytomine server on-platform for domain shift project testing and development purposes

### ISSUE THREAD

**Issue by yohell** [NBISweden/aida-data-hub#449]
Urgent, should be done in the next sprint, the earlier the better.

Has been discussed in [wp2 management](https://docs.google.com/document/d/15aYFGXd1jAZeYFXdjMCpGP7EyszXz3ipUuDK_JsZVw8/edit#heading=h.5zk163vt1zq0) and [PO sync](https://docs.google.com/document/d/1S0R1vaF1bFVhLjD_yV-_MJvl87CwKMhXPqQPQq7xm6M/edit#heading=h.5lqxolqk1r5j) on Mar 7.

The domain shift project (LiU) wants to evaluate whether Cytomine server-as-a-service can be used as an annotation platform, where a RÖ clinical pathologist will annotate 3500 wsi from RÖ (~6 TB, anonymized, potentially for contribution to the Bigpicture project). Cytomine server-as-a-service is one of the options being considered. Annotation activities are to take place Apr 15 - May 10 (week 16-19).

Computational researchers at LiU have been given accounts on https://cytomine.bp.nbis.se/ for initial testing, and AIDA Data Hub is looking into creating a pilot private instance for the researchers for further in-depth testing with private anonymized data. 

This use case is very close to what the Bigpicture platform is envisioned to provide in terms of on-platform services, and could be very valuable in informing project decisions going forward. 

Implementation plan:
- VM deployment
- Password login for researchers
- ~6 TB in total 

Open issues: 
- Direct upload vs. Via Repository (normal upload)
- How to organize images by diagnoses and cases? Maybe Cytomine image groups? Or just projects?)

**Comment by pontus** [comment]
OpenStack has quotas for most consumable resources, including block volumes. Currently, this is set to 1 Tbyte for the aida-hub.bigpicture.se project, which is too small for this. I've sent a mail to hello@safespring.se asking to have it raised to 10 Tbyte for now.
