### ISSUE TITLE
Investigate DICOMweb

### ISSUE THREAD

**Issue by ahembal** [NBISweden/aida-data-hub#456]
Link for [referance](https://www.dicomstandard.org/using/dicomweb)

[Here](https://docs.google.com/document/d/1yjl7OSuyagqaULwoLeSW6GiRy98qu5vxexmdSs6fJPg/edit?usp=drive_link) is the summary of DICOMweb. I also added it into tech seminar topics list. We might consider discussing shortly later.

**Comment by yohell** [comment]
Can we rephrase this card to not be "investigate" but "demo" something from DICOMweb?

**Comment by ahembal** [comment]
IIRC i've heard this from Erik during one of SlideTap meetings. I just wanted to discuss it with the team if we really needed to understand. It doesn't seem like something i can demo but something to acknowledge(?imho).
