### ISSUE TITLE
Investigation Cytomine authentication

### ISSUE THREAD

**Issue by pontus** [NBISweden/aida-data-hub#54]
We would like access to Cytomine to be at smooth as possible, i.e. no separate login with anything resembling username/password.

I believed it was listed with supporting OIDC, but right now I don't see anything such. Given that we almost certainly have some external login (to support bootstrapping the environment, e.g. setting up storage access, possibly launching a private environment and so on), best might be if it can just accept a token (JWT) passed.

**Comment by yohell** [comment]
Who should do this? Cytomine?
