### ISSUE TITLE
Plan acceptance tests

### ISSUE THREAD

**Issue by pontus** [NBISweden/aida-data-hub#552]
We will likely receive new hardware towards the end of august. Once that happens we will do acceptance testing.

We need to both verify that declared values in the offer are what's delivered and perform a short burn-in test.

The performance related metrics we requested were for storage, so `fio` will be the go-to tool there.

For burn-in, we'll need to decide on sensible tests that ideally utilise all relevant parts of the system.

**Comment by yohell** [comment]
Do we have a realistic scientific workload that can be used for this?

**Comment by yohell** [comment]
Tagging @eryl and @minha12 :)

**Comment by pontus** [comment]
Obsolete now.
