### ISSUE TITLE
Fix contents in different buckets

### ISSUE THREAD

**Issue by pontus** [NBISweden/aida-data-hub#59]
Data uploaded to the bigpicture SDA is for unknown reasons currently in different s3 buckets (`bp-archive` and `bigpicture-archive`). It should all be in the `bigpicture-archive` bucket and thus objects in `bp-archive` need to be moved/copied to `bigpicture-archive`.

**Comment by ahembal** [comment]
```
$s3cmd ls --no-check-certificate s3://bp-archive --recursive | wc -l 
5959
$ s3cmd ls --no-check-certificate s3://bigpicture-archive --recursive | wc -l 
9131
```
Now, when I check the objects count, i see there are more objects in the bigpicture-archive than bp-archive.

But if I understand correctly, we have some files in(5959) that are not in (9131), am I right?

**Comment by pontus** [comment]
Last time I checked, there were no name appearing in both. I also checked now and the database in the running setup references names appearing in both the bp-archive and the bigpicture-archive buckets.
