### ISSUE TITLE
Order more disks

### ISSUE THREAD

**Issue by yohell** [NBISweden/aida-data-hub#6]
- [x] get clearance to procure more  disk
- [x] wait for offer
- [x] how many drive bases free (28 slots are empty, 11.8 TB each current installment)
- [ ] coordinate with procurement people, how many disks, what model with right size
- [ ] buy more disk

**Comment by pontus** [comment]
Suitable drive Dell part numbers seem to be:

9HXK6
0JHTD (SED-possible)
YMN53
7KT9W
M1C0T

(from https://www.dell.com/support/manuals/sv-se/powervault-me4084/me4_series_sm_pub/supported-hard-drives?guid=guid-c8dc2942-a352-46cd-8c88-c8a5dde910ae&lang=en-us)

(3,5", 12 TB, 7.2k)

**Comment by pontus** [comment]
0JHTD seems to be cheapest right now, but one will need to visit our purchase coordinator and see what pops up from the channels we have. I expect this to be possible to buy directly using the agreement for Datorkomponenter samt tjänsten att montera och konfigurera specialanpassade datorer.

**Comment by pontus** [comment]
Mail sent to our purchase coordinator, hopefully disks can be ordered before vacation.

**Comment by pontus** [comment]
Order is done (including some back and forth on advania to update it). Not in store so delivery is expected to take 3+ weeks.
