### ISSUE TITLE
Tech Seminar Demo: How to use Kolla Ansible to deploy OpenStack

### ISSUE THREAD

**Issue by yohell** [NBISweden/aida-data-hub#643]
We will need to deploy OpenStack on SDS 2.0, probably several times during acceptance testing and early establishment phase. We anticipate that we will use [Kolla Ansible](https://github.com/openstack/kolla-ansible) for this (fundamental infrastructure as code).

This demo will showcase how to use Kolla Ansible deploy OpenStack.

The goal is to make the rest of the team learn how the system is deployed on the actual system.

**Comment by eryl** [comment]
It's probably a better idea to have this as actual systems deployment on Verdi
