### ISSUE TITLE
Set up suitable custom storage layout in MAAS

### ISSUE THREAD

**Issue by pontus** [NBISweden/aida-data-hub#663]
We want a setup with LVM but that makes it easy to setup mirrors, so it's good if the full device isn't used. Probably this means we a need custom storage layout.

The minimum delivery for this is a storage layout that has EFI and boot partitions and then a smallish root in LVM. For further embellishments one can set up the actual mirroring directly for those machines that should have mirrors, possibly going further but that is much less important than delivering a basic layout that works for everything quickly.

**Comment by minha12** [comment]
A few questions (decision to make):

1. How big should the root partition (/) inside LVM be? (20GB enough?)
2. What percentage/amount of disk space should be left unallocated to allow flexibility for future mirroring (RAID1) (50% is enough or we need an additional small margin, e.g. 52%)?

**Comment by pontus** [comment]
20 Gbyte should be enough I think, but you can check a fresh install (but growing is easy, shrinking is hard).

If we only touch the first disk, one can essentially use all, but same there - it's easy to manage (add) afterwards anyway.

**Comment by minha12** [comment]
Here's a concise report detailing the custom storage layout setup. The layout is aimed to fit an LVM setup with room for future expansions and mirroring options.

#### Storage Layout Summary

The storage layout is configured with an (1) EFI and a boot partition, (2) small sized root partition within an LVM. The majority of the disk space is left unallocated within the volume group (for easy future expansions or additional logical volumes).

#### Layout Table

| Name             | Size          | Type                | Filesystem | Mount point  |
|------------------|---------------|--------------------|------------|--------------|
| `nvme0n1`        | 480.03 GB     | disk                | -          | -            |
| `nvme0n1-part1`  | 536.87 MB     | part (EFI)          | FAT32      | `/boot/efi`  |
| `nvme0n1-part2`  | 479.49 GB     | part (LVM PV)       | -          | -            |
| `vgroot`         | 479.49 GB     | lvm-pv(nvme0n1-part2) | -          | -            |
| `vgroot-lvroot`  | 20.36 GB      | lvm                 | ext4       | `/`          |
| **Unallocated in `vgroot`** | **459.13 GB** | lvm                 | -          | -            |


This layout was achieved using a single command in the MAAS CLI, provided that the size of the logical volume for the root partition to be 20 GB. The command used is as follows:

```bash
maas minhha-maas machine set-storage-layout 6wctrx storage_layout=lvm lv_size=21474836480 # 20GB
```
- `6wctrx` is `system_id` 
- `minhha-maas` is a maas profile

Note: to get all the system_id and their hostname:

`maas minhha-maas machines read | jq -r '.[] | "\(.hostname) \(.system_id)"'`

Sources: 
[1] https://github.com/CanonicalLtd/maas-docs/blob/master/en/manage-cli-advanced.md#set-the-default-storage-layout
[2] https://github.com/CanonicalLtd/maas-docs/blob/master/en/installconfig-storage.md

**Comment by pontus** [comment]
Great, that looks good (the documentation I checked didn't mention any options for LVM, guess I didn't look deep enough). Can that be set on the default layout as well?

**Comment by minha12** [comment]
Hi, I tried to look for options to change the lvm default setup with customed lv_size, but apparently, it was not supported. I do see that we can set up a custom layout using Commissioning scripts; it could be complicated, though. Alternatively, we can run the above command for all the machines (or selected machines) with bash script, for example:

```bash
for node in node{01..n}; do
  maas $PROFILE machine set-storage-layout $node storage_layout=lvm lv_size=21474836480
done
```

**Comment by pontus** [comment]
Okay, thanks, yes, together with #673 that should be enough.
