### ISSUE TITLE
Homework for helm presentation on 15/02

### ISSUE THREAD

**Issue by shreyasshivakumara** [NBISweden/aida-data-hub#73]
Links for reference:

https://helm.sh/docs/
https://github.com/NBISweden/beacon-helm
https://github.com/neicnordic/sda-helm/tree/master/charts/sda-mq

**Comment by ahembal** [comment]
Some other links: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#deployment-v1-apps
