### ISSUE TITLE
Figure out DNS

### ISSUE THREAD

**Issue by pontus** [NBISweden/aida-data-hub#732]
Where does verdi belong naturally DNS-wise, any rules or other considerations to keep in mind? How difficult are updates at various places?

Possible options /could/ be under:
* datahub.aida.scilifelab.se
* nbis.se 
* cmiv.liu.se
* medtech4health.se
* something else? 

One name for admin VPN, one name for user access:
dsp.aida.scilifelab.se?  (customer portal)
dsp-admin.aida.scilifelab.se? (admin)

**Comment by yohell** [comment]
After talking to CMIV/AIDA management it seems like aida.scilifelab.se could be a sensible home for sevices, like dsp.aida.scilifelab.se or similar.
