### ISSUE TITLE
Nvidia GPUs; would we prefer A40 or A100?

### ISSUE THREAD

**Issue by pontus** [NBISweden/aida-data-hub#89]
Using A100 would allow for larger resources given to a single project which might be helpful for some projects at time but are likely more expensive.

Often a single A100 will be too large to be suitable and we'd prefer to offer resources from the same physical GPU to different projects, what would the requirements be for being able to do that?

**Comment by yohell** [comment]
Is this regarding Bigpicture or CMIV research database 2.0? If the latter, then I think the wisest course of action is A40, for multiple reasons. If Bigpicture, then I don't know :D

**Comment by pontus** [comment]
Depends on simpler means "most restrictive" :)

I'm still working to understand some of the things and their properties, but in short, I mostly see a possible issue if A40s would allow us to provide 1 or 2 GPU enabled VMs per hypervisor node (whereas 2 A100s could possibly be split for up to 14 GPU enabled VMs). A100s also support larger workloads as well although I'm not sure if that would be important for someone.

(Being able to provide small allocations can often help avoid problems with irritation about policies/their consequences and serve as an enabler to help people move beyond their desktop systems.)

**Comment by yohell** [comment]
Ah, alright! I will happily yield the decisions of "wiser" to you :-)

**Comment by yohell** [comment]
I've asked Johan to procure A40 for Bigpicture based on the analysis report you made!
